### ISSUE TITLE
Is there a preprint for your work?

### ISSUE THREAD

**Issue by qwefhajk** [diego-hayashi/fenics_topopt_foam#1]
Is there a preprint of your article? I can't wait to see how it works.

**Comment by diego-hayashi** [comment]
No. However, since it has just been accepted for publication, it should appear after some time in < https://link.springer.com/journal/158/online-first >.

**Comment by diego-hayashi** [comment]
Published in < https://doi.org/10.1007/s00158-021-03061-4 >.
